### ISSUE TITLE
why is netlify failing unless i clear cache and redeploy

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#130]
Recently, my netlify builds on adage-frontend started failing until I go in and manually re-run them with the clear cache option.

For example, here is one that failed:
https://app.netlify.com/sites/adage-frontend/deploys/5e852ef33473ae0006386745

And the manual retry was fine:
https://app.netlify.com/sites/adage-frontend/deploys/5e852f81b140ab00118ce435

I figured it started happening because I added some more dependencies that took longer to fetch and install, and just made the deploy time-out. But I'm not sure.

**Comment by vincerubinetti** [comment]
My issue on Netlify about this:
https://community.netlify.com/t/builds-always-fail-until-clearing-cache-and-re-trying/11612

Related issues:
https://community.netlify.com/t/build-failures-on-every-push-except-pass-on-cache-rebuild/8727
https://community.netlify.com/t/site-deploy-fails-unless-netlify-s-build-cache-is-cleared/12417
https://github.com/facebook/create-react-app/issues/8751
https://github.com/facebook/create-react-app/issues/7183

**Comment by joshuawootonn** [comment]
Having the same issue. Just glad at least manually retrying fixes this!

**Comment by vincerubinetti** [comment]
I finally managed to solve this in a kludge-like way: I created one of the new Netlify build plugins to clear the yarn  cache before each install.

In `./netlify/plugin/index.js`:

```javascript
const util = require('util');
const exec = util.promisify(require('child_process').exec);

module.exports = {
  async onInit() {
    console.log('deleting node_modules');
    await exec('rm -rf node_modules');
    console.log('clearing yarn cache');
    await exec('yarn cache clean');
    console.log('running yarn install');
    await exec('yarn install');
  }
};
```

In `.neltlify/plugin/manifest.yml`:

```yaml
name: netlify-plugin-clear-cache
```

In `netlify.toml`:

```toml
[[plugins]]
package = "./.netlify/plugin"
```

All this does is clear the `node_modules` directory, clear the yarn cache, and reinstall all the yarn packages. Netlify is already installing yarn packages before this step, so this will at least double the time it takes to make pull request deploy previews, for example. But at least I don't have to keep manually clicking "clear cache and redeploy", and sometimes forgetting, and ending up with red x's all over my github commit history.

I suppose you could accomplish the same thing by just adding the `yarn cache clean` and etc. commands to your `npm run build` script.

**Comment by vincerubinetti** [comment]
It seems like this issue might ultimately be due to this issue:
https://github.com/netlify/build-image/issues/196

I think one of my dependencies `stdlib` is a monorepo, and I believe it also compiles to binary or web assembly or something, which [the guide](https://community.netlify.com/t/common-issue-my-site-deploy-fails-unless-netlifys-build-cache-is-cleared/3035) said might be a problem because it doesn't get re-built. I've frequently had problems with it running correctly locally until I clear the yarn cache and reinstall. And although my memory is hazy, I think the Netlify pull request previews started failing around the same time I added this library to my project.
