### ISSUE TITLE
select all genes related to search term

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#131]
*From Dallas Mould:*

I like that selecting a gene redirects me to pseudomonas.com, and that the multi-search feature allows the search of strings like “reductase” and gene number at the same time. If I search “citrate” and I click the select button, however, the select button only allows me select the first gene in each search term. I think it would be nice to have an option in this case to select all the genes so that I could create a list of genes related to the term “citrate” rather than clicking them all one by one.

**Comment by vincerubinetti** [comment]
A problem with this is that the search results might not be exactly what you expect them to be, unless we work really hard to fine tune the searching with @dongbohu. It's not like google where you can guarantee that the first 10 results will really be related to what you're looking for.

But assuming you're okay with that, I have a question. Would you ever want to do this with multiple search terms? If so, we could do something like this:

![image](https://user-images.githubusercontent.com/8326331/78272423-7fdbea00-74db-11ea-90eb-396eef65a99a.png)

If you'd only want to do it with one search term at a time (more likely imo), then my solution would be to add shift+click or click+drag abilities to the checkboxes in the table, to allow you to more easily select multiple entries.

**Comment by dongbohu** [comment]
The backend also supports full text searches, which can have multiple terms, but it has to be exact match of the word stem, so the search terms don't allow typos.

**Comment by vincerubinetti** [comment]
I'll add a button under the single search to "select all displayed results". I should also rename the text under the mutli search to "select/deselect each first result". A bit more clear than just "select/deselect first results".

**Comment by vincerubinetti** [comment]
Nvm, decided to add shift+click instead, as I think it's more flexible and clean than having a button to select all of the displayed results.
