### ISSUE TITLE
Add link to publication in experiment description or separate field for url

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#135]
*From Dallas Mould:*

For the experiment selection, I like the paragraph describing the design/results, but I think it would be nice to have a link to the publication if possible.

**Comment by vincerubinetti** [comment]
@dongbohu @cgreene

**Comment by dongbohu** [comment]
I have two questions:
(1) Does each experiment have either zero or one publication URL?
(2) Where can I find each experiment's publication URL (if it exists)?

**Comment by cgreene** [comment]
@dongbohu : I think some might have multiple publications but I'm not sure. I think the experiment identifiers that we have are ArrayExpress ones:
https://www.ebi.ac.uk/arrayexpress/experiments/E-MEXP-31/

I think it does have a JSON API.

**Comment by vincerubinetti** [comment]
Marking this as an enhancement as it doesn't seem 100% necessary for MVP.

**Comment by vincerubinetti** [comment]
Moving this issue to the backend since it's really a backend issue. If ever added to the experiment metadata, this field will automatically show up on the experiment details page.
