### ISSUE TITLE
Find better way to link sample heat map to sample group table

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#136]
Currently we have two tables of information on top of each other that are conceptually linked:

![image](https://user-images.githubusercontent.com/8326331/78270503-e7dd0100-74d8-11ea-918e-3cfc433ec909.png)

When we cluster by sample in the heatmap, we're sorting the rows. Should that also automatically sort the sample group table below it in the same order? And vice versa?

The intent is to allow users to cluster the heatmap, then group the samples based on what they see in the heatmap.

**Comment by georgiadoing** [comment]
Yes, it would be awesome to be able to order the rows of the heatmap in accordance with the sample group table! Sometimes the manual ordering of the heatmap based on experimental setup is really useful.

**Comment by vincerubinetti** [comment]
Closed by #168
