### ISSUE TITLE
have keyboard shortcuts to jump to sections on page

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#139]
*From Georgia Doing:*

When looking at the results of a gene search, is there a way to have a quick navigation down to the enriched signatures that is quicker than scrolling? At first when I did a search I simply didn’t scroll down far enough and missed the signatures but if there was a button to ‘jump’ down to the signature results it may have reminded me they were there

**Comment by vincerubinetti** [comment]
@georgiadoing It isn't typical to do keyboard shortcuts for navigation between vertical sections on webpages. Most people just use page up/down to skip faster.

What we could do:
1) have the number keys 1,2,3... jump you do the 1st, 2nd, 3rd, etc section on the page
2) have a tiny floating "table of contents" on the side of the page, visible at all times (only on desktop though, when the screen is wide enough and has white space on the sides) with the section names, and you could click them to jump to the section

Marking this as an enhancement since it's probably not needed for MVP. Solution 1 could be done in 5 minutes. Solution 2 would take a bit more time.

**Comment by georgiadoing** [comment]
OK - also may just be a me-specific thing, if it is not typical than I think it is fine to skip :)
