### ISSUE TITLE
include PA14 homologue number for genes?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#140]
*From Georgia Doing:*

Could we include PA14 homologue number in the gene tables? Pa biologists would use that more than Entrez ID, but if both fit that could be nice too

---

Possibly related to #133 ?

**Comment by vincerubinetti** [comment]
@georgiadoing Is the PA14 homologue number different from the standard name or systematic name? If so, we'd need to add another field to the database @dongbohu 

But if you mean that some places in the app are showing the entrezid where they should be showing the standard or systematic name, then see #133

**Comment by georgiadoing** [comment]
There are two main strains of P. aeruginosa so kind of like two main reference genomes as well. Many of the genes between the two are homologous. As I understand it PAO1 number (eg PA0001) is our standard name, letter-based name (eg dnaA) is our systemic name (is this right?) and it could useful if another field could be added with PA14 name (eg PA14_00010). Not all PAO1 genes have PA14 homologs, but many do, and that information can be very useful to include when available. Fewer microbiologists I know are as used to using entrezids as PAO1 or PA14 numbers, though I know I can't speak for the whole field or any users from other fields... especially computational ones...

**Comment by vincerubinetti** [comment]
@cgreene thoughts on this?

**Comment by dongbohu** [comment]
@georgiadoing: The PA14 homologs are only available for P. aeruginosa organism, right? If they are, then it probably makes more sense to load these names into `aliases` field in the database.

**Comment by cgreene** [comment]
I agree aliases

**Comment by dongbohu** [comment]
@cgreene and @georgiadoing: Is there a text file online that maps a gene's standard or systematic name to PA14 name?
