### ISSUE TITLE
allow samples from multiple experiments to be mixed

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#145]
*From Georgia Doing:*

I know the old server allowed samples from multiple experiments to be added to the ‘basket’ – is that something we are keeping? I liked it, but if it is overcomplicating things I wouldn’t say I need it.. it was cool though

**Comment by vincerubinetti** [comment]
Per discussions with @cgreene , we're not keeping this feature. Apparently, it's difficult to combine samples from different experiments without making mistakes with respect to scientific accuracy. And supposedly most users will not use this feature.

From my end it wouldn't be too terrible. I'd change the experiment search from radio buttons to checkboxes, change the selected experiment section to a table, add experiment details to the sample groups table, and some under-the-hood changes. Not a 5 minute change, but probably not more than a day or two.

**Comment by cgreene** [comment]
Let's leave it at a not-for-MVP. I worry a lot about how confusing it could be to new users.

**Comment by vincerubinetti** [comment]
Agreed. Seems like a human error trap. Less informed users may think they can mix-and-match samples from different experiments without any thought and completely trust the results as is.

**Comment by georgiadoing** [comment]
Roger that - you guys  make good points about confusing users and leading people to wrong conclusions.
