### ISSUE TITLE
grouping just one sample stalls page

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#148]
*From Georgia Doing:*

As I was making my volcanos, if I just selected one sample for a group the page seemed to stall, blank-out and reload in a loop that I couldn’t get out of – maybe display a message to avoid this error?

**Comment by vincerubinetti** [comment]
@georgiadoing I haven't been able to replicate this bug. Can you find a reliable way to reproduce it, and send me the link? Also can you tell me what operating system you're on, and what browser you're using.

**Comment by georgiadoing** [comment]
I also have not replicated it - tried with a few different experiments this morning... I didn't keep track of which experiment I was looking at when this happened either.. sorry, maybe it was just something about chrome  (or me) that day..

**Comment by vincerubinetti** [comment]
No problem. Will close this for now.

Also, it might be helped by #162 that I just merged. I realized that any time a user grouped a sample, the heatmap above would re-render, which is very slow because it has to draw thousands of colored rectangles. That shouldn't happen anymore, so grouping should be more responsive.
