### ISSUE TITLE
review text content of the app

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#161]
I'll need help from @cgreene @ajlee21 @georgiadoing and others to review the text content of the app that talks about biology and machine learning concepts that I am not qualified to verify.

Mostly on the home page and the about/help page.

We also may want a sentence at the start of each section that explains what the section is about, sort of like some places in the old adage has:

![image](https://user-images.githubusercontent.com/8326331/79519276-6a110d80-8021-11ea-92a4-b6b8b91466a9.png)

**Comment by ajlee21** [comment]
**On the landing page:**
- The page looks so clean and I love the colors and fonts!
- Do we want to change the text to  `ADAGE is a tool to help you explore and discover new insights about P. aeruginosa from machine learning models`? Since ADAGE was specifically tuned for P. aeruginosa and that's currently the only data we have available?  Or do we want to keep this more general anticipating that in the future we will have other models and datasets?
- Is this `See canonical/curated gene sets that significantly overlap with a signature's associated genes.` missing a hyperlink?

**Comment by cgreene** [comment]
I think we should keep the tool itself general re: it's application areas/organisms.

**Comment by ajlee21** [comment]
**Help page:**
- Again, the layout and all the details look SO beautiful
- Couldn't find the instructions for uploading a different model on github?
- Minor text fix in `Expression compendium` `Aeruginosa` should be lower case

**Comment by ajlee21** [comment]
**Experiments page**
- Do we want to add threshold for the volcano plot?
- Not sure if this is something that any user will do, but it looks like the volcano display needs a minimum of 4 samples to run. Not sure if we want to add text to note that to users...Or if that is a use case that will likely not occur so we don't have to worry about it

**Comment by georgiadoing** [comment]
I agree with @cgreene about keeping the tool description general with respect to organisms on the landing, but maybe we want to specify that it is gene expression? Maybe 

"Adage is a tool to help you explore gene expression data and discover new insights from transcriptional patterns that emerge in machine learning models"

Just throwing it out there, but don't want to get jargon-y either..

**Comment by vincerubinetti** [comment]
FWIW, the point of the home page, in my mind, is to serve as an advertisement for the app and a very brief, high-level description of what the app can do. I'd like to keep away from specifics if possible.

> Is this See canonical/curated gene sets that significantly overlap with a signature's associated genes. missing a hyperlink?

The paragraphs on the home page are just describing what you can do on each of the three main pages in the app, by section. Were you expecting each sentence to link to the specific section on the page that it's talking about? Because we can do that.

> Couldn't find the instructions for uploading a different model on github?

Yeah we still need to add this. I figured the readme of the front and backend repos would be the right place to explain how to edit things, rather than in the app text itself.

> Minor text fix in Expression compendium Aeruginosa should be lower case

Will fix.

> Do we want to add threshold for the volcano plot?

I could add a slider for this. Would you want to filter by p-value or mean diff, or both?

> Not sure if this is something that any user will do, but it looks like the volcano display needs a minimum of 4 samples to run. 

Yeah you need at least 2 samples in each group to run, i believe because that's required for the student t-test that calculates the volcano data. I sort of indicate that there's insufficient data to show the volcano plot here:
![image](https://user-images.githubusercontent.com/8326331/79891194-a603f400-83ce-11ea-97e4-f74d0275903c.png)
But I'll make this warning a bit more specific.

**Comment by vincerubinetti** [comment]
> I think we should keep the tool itself general re: it's application areas/organisms.

If this is the case, should I omit all the stuff about the specific built-in models on the help page?

**Comment by ajlee21** [comment]
```The paragraphs on the home page are just describing what you can do on each of the three main pages in the app, by section. Were you expecting each sentence to link to the specific section on the page that it's talking about? Because we can do that.```

I realized I misunderstood the sentence when I initially read this so I think its fine as is. You already link out to the respective pages.

**Comment by vincerubinetti** [comment]
From our slack conversation:

In general, the home page should be a high level overview of Adage and an advertisement. It should lean more towards answering the question "why" rather than "how". Why is this important. What is the motivation. What can you get out of it.

Notes from Casey on homepage:

Adage helps you explore gene expression and discover new insights from machine learning models

Adage helps you explore gene expression data and discover new insights from machine learning models

See how genes relate to each other, other genes, and how they are represented in machine learning signatures. Visualize your model's gene network as an interactive graph display. (edited) 
4:13
:point_up::skin-tone-2: instead of "Find signatures that significantly overlap with the genes you're interested in to interpret underlying biological processes. Visualize your model's gene network as an interactive graph display."
4:15
"Find the genes that most strongly influence a signature's activity. Explore experiments with the highest range of activities within a signature. See canonical/curated gene sets that significantly overlap with a signature's associated genes."
Perhaps:
"Understand signatures from machine learning models by exploring the genes that contribute, the experiments in which they vary the most, and which pathways they significantly overlap with."

**Comment by vincerubinetti** [comment]
A bunch of people have reviewed the text and given feedback. Closing this for now. Will accept new issues for specific text revision requests.
