### ISSUE TITLE
figure out how to handle empty search

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#176]
When nothing is typed into a search box, some results still display below it. This is so people can jump right in more easily, with less steps.

But it also confuses people. What are those results, are they arbitrary, did I accidentally type something into the search, are they all of the genes, are they special.

Should we pre-populate each search box with something, eg "dna" for genes. Should we only show the top 5 results when nothing's typed in to make it clear it's not all of the genes in the database. Should we put a note between the search box and the result table that says "try these" to indicate it's a blank search.

**Comment by vincerubinetti** [comment]
![GJaV0ONXGU](https://user-images.githubusercontent.com/8326331/81191064-94058200-8f86-11ea-8211-0525afe90cc4.gif)

potential solution?

**Comment by vincerubinetti** [comment]
@cgreene @debhogan-208 Thoughts? This is an issue we should address before the full launch,

**Comment by cgreene** [comment]
I like the potential solution. Let me slack this to Deb as well to see if she has some thoughts before you implement that though.

**Comment by vincerubinetti** [comment]
Only problem with that potential solution is that, because it's grayed out, people might think they can't click on it.

**Comment by debhogan-208** [comment]
When I search sahh I don’t get a hit now…I need the capital letter to match. Too stringent?
Other things look good.

**Comment by vincerubinetti** [comment]
I get a hit for "sahh"?

![image](https://user-images.githubusercontent.com/8326331/82365390-97652880-99de-11ea-90e7-2733391848ec.png)


Works in multi-gene search too...
