### ISSUE TITLE
Tags/keywords

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#194]
For Github:

![image](https://user-images.githubusercontent.com/8326331/86307423-bf05fe00-bbe4-11ea-8e8e-82946df94439.png)

and for metadata and SEO on the actual webapp.

Here's what I have. Let's get a bunch more. @cgreene @ajlee21 @debhogan-208 @georgiadoing 

---

web app, machine learning, neural networks, bioinformatics, computational biology, genomics, gene expression, science, education, research, academic, open source

**Comment by dongbohu** [comment]
`Pseudomonas` maybe? (I know the app supports multiple species, but it is focused on Pseudomonas now.)

**Comment by ajlee21** [comment]
`gene expression`?
`neural networks`?

What are these keywords used for? Is it when people are search for the app?

**Comment by vincerubinetti** [comment]
@ajlee21 Basically yeah.

**Comment by cgreene** [comment]
I propose: `bioinformatics` `machine learning` `genomics` `gene expression` `neural networks` and leaving pseudomonas off the github portion, since that could be deployed for any organism's model.
