### ISSUE TITLE
Selected genes should be prioritized with an empty search

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-frontend#33]
On the genes page, search for a gene (for example, `anr`), which is not on the front page. Select it. Clear the search. The selected gene presumably ends up somewhere else in the sorted list. If the page is empty and nothing is included in the search box, selected genes should probably be prioritized.

https://py3-adage.greenelab.com/genes

**Comment by vincerubinetti** [comment]
This will be addressed by the section below the search. It will show a table of all the selected genes, which will show all of the gene data fields, allow the user to sort by any field, and allow the user to deselect certain genes or all genes very quickly.

If the user had 100 genes selected, and we showed the selected genes first in the search results, the user wouldn't see what they were searching for. As such, I think we want a separation as to what is in the two sections. The search section lists the genes relevant to whatever the user has searched for (with whatever filters we add in the future), and the "selected" section shows all the genes the user has chosen to analyze.
